#pragma once 
#ifndef SAF_BOOLSETTINGS
#define SAF_BOOLSETTINGS

#define SMP_BOOL_SETTINGS_EMPTY_TRACKS_RMV 0b1u
#define SMP_BOOL_SETTINGS_REMNANTS_RMV 0b10u
#define SMP_BOOL_SETTINGS_ALL_INSTRUMENTS_TO_PIANO 0b100u
#define SMP_BOOL_SETTINGS_IGNORE_TEMPOS 0b1000u
#define SMP_BOOL_SETTINGS_IGNORE_ALL_BUT_TEMPOS_NOTES_AND_PITCH 0b10000u
#define SMP_BOOL_SETTINGS_IGNORE_PITCHES 0b100000u
#define SMP_BOOL_SETTINGS_IGNORE_NOTES 0b1000000u

enum _BoolSettings {
	remove_empty_tracks = SMP_BOOL_SETTINGS_EMPTY_TRACKS_RMV,
	remove_remnants = SMP_BOOL_SETTINGS_REMNANTS_RMV,
	all_instruments_to_piano = SMP_BOOL_SETTINGS_ALL_INSTRUMENTS_TO_PIANO,
	ignore_tempos = SMP_BOOL_SETTINGS_IGNORE_TEMPOS,
	ignore_all_but_tempos_notes_and_pitch = SMP_BOOL_SETTINGS_IGNORE_ALL_BUT_TEMPOS_NOTES_AND_PITCH,
	ignore_pitches = SMP_BOOL_SETTINGS_IGNORE_PITCHES,
	ignore_notes = SMP_BOOL_SETTINGS_IGNORE_NOTES
};

using BIT = bool;

#endif 