#pragma once 
#ifndef SAF_BOOLSETTINGS
#define SAF_BOOLSETTINGS

#define SMP_BOOL_SETTINGS_EMPTY_TRACKS_RMV (1 << 0)
#define SMP_BOOL_SETTINGS_REMNANTS_RMV (1 << 1)
#define SMP_BOOL_SETTINGS_ALL_INSTRUMENTS_TO_PIANO (1 << 2)
#define SMP_BOOL_SETTINGS_IGNORE_TEMPOS (1 << 3)
#define SMP_BOOL_SETTINGS_IGNORE_ALL_BUT_TEMPOS_NOTES_AND_PITCH (1 << 4)
#define SMP_BOOL_SETTINGS_IGNORE_PITCHES (1 << 5)
#define SMP_BOOL_SETTINGS_IGNORE_NOTES (1 << 6)
#define SMP_BOOL_SETTINGS_ENABLE_IMPORTANT_FILTER (1 << 7)
#define SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_NOTES (1 << 8)
#define SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_PITCH (1 << 9)
#define SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_TEMPO (1 << 10)
#define SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_PROGC (1 << 11)
#define SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_OTHER (1 << 12)

enum _BoolSettings 
{
	remove_empty_tracks = SMP_BOOL_SETTINGS_EMPTY_TRACKS_RMV,
	remove_remnants = SMP_BOOL_SETTINGS_REMNANTS_RMV,
	
	all_instruments_to_piano = SMP_BOOL_SETTINGS_ALL_INSTRUMENTS_TO_PIANO,
	ignore_tempos = SMP_BOOL_SETTINGS_IGNORE_TEMPOS,
	ignore_all_but_tempos_notes_and_pitch = SMP_BOOL_SETTINGS_IGNORE_ALL_BUT_TEMPOS_NOTES_AND_PITCH,
	ignore_pitches = SMP_BOOL_SETTINGS_IGNORE_PITCHES,
	ignore_notes = SMP_BOOL_SETTINGS_IGNORE_NOTES,
	
	enable_important_filter = SMP_BOOL_SETTINGS_ENABLE_IMPORTANT_FILTER,
	imp_filter_allow_notes = SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_NOTES,
	imp_filter_allow_pitch = SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_PITCH,
	imp_filter_allow_tempo = SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_TEMPO,
	imp_filter_allow_progc = SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_PROGC,
	imp_filter_allow_other = SMP_BOOL_SETTINGS_IMP_FILTER_ALLOW_OTHER,
};

using BIT = bool;

#endif 